### PR TITLE
Make Docker image smaller (no-recommends + Headless JRE)

### PR DESCRIPTION
**Pull request by beelux**
To make the Docker image lighter:
- I've removed "recommended" but useless packages (~300MB)
- I've also changed the Java JDK to a Headless JRE which uses considerably less space (~269MB)

The Go toolchain could still be removed by building a static binary, but this would require some more work throughout the codebase.

### CODE REVIEW

**Comment by beelux** [comment]
Using `--no-install-recommends` also removes a lot of packages, which removes most text editors, so possibly we could add `vim` and `nano` back into the image.

**Comment by beelux** [comment]
Oh, and I've also modified the base image tag.
Currently, `latest` is `jammy`, but this will change as new LTS versions come out. As to avoid the base image randomly changing in the future to 24.04 by itself, i've changed it to jammy (22.04).

**Comment by beelux** [comment]
I've tested the follwoing with this Dockerfile:
- [X] Chat Client
- [ ] DNS (probably client)
- [X] HTTP (some tests failing, probably code-related)
- [X] Chat Server (some tests failing, probably code-related)
- [X] Unreliable Chat (some tests failing, probably code-related)

Most of the issues seem to be specfic to current sample code.

**Review by fzovpec — APPROVED** [review]
lgfm!

**Pull request merged**
